In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import r2_score, accuracy_score, precision_score

In [ ]:
df = pd.read_csv("/content/insurance.csv")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [ ]:
cat_col = df.select_dtypes(include="object")

In [ ]:
le = LabelEncoder()

In [ ]:
for i in cat_col:
  df[i] = le.fit_transform(df[i])

In [ ]:
x = df.drop(columns=["charges"])
y = df["charges"]

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [ ]:
models = {
    "dt" : DecisionTreeRegressor(max_depth=10),
    "rf" : RandomForestRegressor(n_estimators=50)
}

In [ ]:
for name, model in models.items():
  model.fit(x_train, y_train)
  y_pred = model.predict(x_test)
  print(name, r2_score(y_test, y_pred))

dt 0.7317948769579556
rf 0.8669127996873369

In [ ]:
df = pd.read_csv("/content/Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
cat_columns = df.select_dtypes(include="object")

In [ ]:
for i in cat_columns:
  df[i] = le.fit_transform(df[i])

In [ ]:
# df.head(2)

In [ ]:
x1 = df.drop(columns=["Exited"])
y1 = df["Exited"]

In [ ]:
x_train1, x_test1, y_train1, y_test1 = train_test_split(x1, y1, test_size=0.20, random_state=42)

In [ ]:
models = {
    "lr" : LogisticRegression(),
    "dt" : DecisionTreeClassifier(max_depth=20),
    "rf" : RandomForestClassifier(n_estimators=50)
}

In [ ]:
for name, model in models.items():
  print(name, model)
  model.fit(x_train1, y_train1)
  y_pred = model.predict(x_test1)
  print(name, accuracy_score(y_test1, y_pred))

lr LogisticRegression()
lr 0.8035
dt DecisionTreeClassifier(max_depth=20)
dt 0.7945
rf RandomForestClassifier(n_estimators=50)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

rf 0.863