In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('placement - placement.csv')

In [3]:
df.head(2)

   cgpa  resume_score  placed
0  8.14          6.52       1
1  6.17          5.17       0

In [5]:
df.empty

False

In [7]:
x = df.drop(columns='placed') 
y = df['placed']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [15]:
np.round(x_train.describe(), 2)

        cgpa  resume_score
count  80.00         80.00
mean    6.95          7.00
std     1.13          1.01
min     5.27          4.95
25%     6.00          6.28
50%     6.62          7.15
75%     8.06          7.69
max     9.31          9.06

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [11]:
mm = MinMaxScaler()

In [12]:
x_train_mm = mm.fit_transform(x_train)

In [13]:
x_train_new = pd.DataFrame(x_train_mm, columns=x_train.columns)

In [14]:
np.round(x_train_new.describe(),2)

        cgpa  resume_score
count  80.00         80.00
mean    0.42          0.50
std     0.28          0.25
min     0.00          0.00
25%     0.18          0.32
50%     0.33          0.54
75%     0.69          0.67
max     1.00          1.00