# Decision Tree model

In [24]:
# Decision tree model --> CART(Classificatoin And Regression Tree)

# When data is numerical --> branch individual output average --> final output 
# when data is categorical --> branch individual output (100 covid patients) --> 70 yes and 30 no -> final o/p -> 70 yes
# loss - -p_yes*log_yes - p_no*log_no

In [ ]:
# When data is numerical

In [1]:
import numpy as np 
import pandas as pd

In [3]:
df = pd.read_csv('insurance - insurance.csv')
df.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le = LabelEncoder()

In [7]:
df['sex'] = le.fit_transform(df['sex'])
df['smoker'] = le.fit_transform(df['smoker'])
df['region'] = le.fit_transform(df['region'])

In [18]:
x = df.drop(columns=['charges'])
y = df['charges']

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [25]:
from sklearn.tree import DecisionTreeRegressor

In [26]:
dt = DecisionTreeRegressor()

In [27]:
dt.fit(x_train, y_train)

DecisionTreeRegressor()

In [28]:
y_pred = dt.predict(x_test)

In [30]:
from sklearn.metrics import r2_score

In [31]:
r2_score(y_test, y_pred)

0.7057004055340583

In [32]:
# When target data is numerical

In [33]:
df = pd.read_csv("Social_Network_Ads - Social_Network_Ads.csv")
df.head(3)

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0

In [45]:
df['Gender'] = le.fit_transform(df['Gender'])

In [46]:
x = df.drop(columns=['Purchased'])
y = df['Purchased']

In [47]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state = 42)

In [48]:
from sklearn.tree import DecisionTreeClassifier

In [49]:
dt = DecisionTreeClassifier()

In [50]:
dt.fit(x_train, y_train)

DecisionTreeClassifier()

In [51]:
y_pred = dt.predict(x_test)

In [52]:
from sklearn.metrics import accuracy_score

In [53]:
accuracy_score(y_test, y_pred)

0.9

In [54]:
# covid data = dDecisionTreeClassifier --> model_accuracy