In [66]:
import numpy as np 
import pandas as pd

In [67]:
df = pd.read_csv('covid_toy.csv')
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [68]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [69]:
df['fever'] = df['fever'].fillna(df['fever'].mean())

In [70]:
df['cough'].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [71]:
df.drop(columns=['city'],inplace=True)

In [72]:
df['gender'] = df['gender'].map({'Male':1, 'Female':0})
df['cough'] = df['cough'].map({'Mild':0, 'Strong':1})
df['has_covid'] = df['has_covid'].map({'No':0, 'Yes':1})

In [73]:
from sklearn.model_selection import train_test_split

In [74]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [75]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [76]:
np.round(x_train.describe())

        age  gender  fever  cough
count  80.0    80.0   80.0   80.0
mean   43.0     0.0  101.0    0.0
std    24.0     0.0    2.0    0.0
min     5.0     0.0   98.0    0.0
25%    20.0     0.0  100.0    0.0
50%    42.0     0.0  101.0    0.0
75%    65.0     1.0  102.0    1.0
max    84.0     1.0  104.0    1.0

In [77]:
from sklearn.preprocessing import StandardScaler

In [78]:
sc = StandardScaler()

In [79]:
x_train_sc = sc.fit_transform(x_train)  ### fit means learn the parameters and transform means apply on that

In [80]:
type(x_train_sc)

numpy.ndarray

In [81]:
x_train_new = pd.DataFrame(x_train_sc, columns=x_train.columns)

In [82]:
x_train_new

         age    gender     fever     cough
0   1.566141 -0.837931  0.009126 -0.816497
1  -1.558945 -0.837931 -0.512343 -0.816497
2  -0.983271 -0.837931 -0.512343 -0.816497
3  -0.654315  1.193416 -0.512343 -0.816497
4   1.237185 -0.837931  1.052064 -0.816497
..       ...       ...       ...       ...
75 -0.777674 -0.837931  0.530595  1.224745
76  1.319424 -0.837931  1.573533  1.224745
77  0.332554  1.193416  1.573533 -0.816497
78  1.607261 -0.837931  0.530595  1.224745
79 -1.312228 -0.837931 -0.512343  1.224745

[80 rows x 4 columns]

In [84]:
np.round(x_train_new.describe(),2)

         age  gender  fever  cough
count  80.00   80.00  80.00  80.00
mean   -0.00    0.00  -0.00  -0.00
std     1.01    1.01   1.01   1.01
min    -1.56   -0.84  -1.56  -0.82
25%    -0.94   -0.84  -0.51  -0.82
50%    -0.04   -0.84   0.01  -0.82
75%     0.91    1.19   0.53   1.22
max     1.69    1.19   1.57   1.22