In [1]:
# Ordinal Encoding ---> 
# Label Encoding --> column[sub1, sub2, sub3....subn] --> encode 
# Ordinal Encoding --> column[sub1, sub2, sub3....subn] --> Re-Arrange--> encode

In [28]:
# LabelEncoder --> When we have singal column
    # --> we can not set sub-category form 
    # has_covid['yes', 'no'] --> labelEncoder --> [1,0]

# OrdinalEncoder --> When we have multiple columns 
                # --> We can set sub-category forms
                # has_covid['yes', 'no'] --> OrdinalEncoder --> [0.1]

In [29]:
import numpy as np 
import pandas as pd

In [30]:
df = pd.read_csv('covid_toy.csv')
df.head(3)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes
2   42   Male  101.0  Mild    Delhi        No

In [31]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [32]:
df.dropna(inplace=True)

In [33]:
df.drop(columns=['city', 'age', 'fever'], inplace=True)

In [34]:
df.head(3)

  gender cough has_covid
0   Male  Mild        No
1   Male  Mild       Yes
2   Male  Mild        No

In [35]:
from sklearn.preprocessing import OrdinalEncoder

In [36]:
oe = OrdinalEncoder(categories=[['Female', 'Male'], ['Mild', 'Strong'], ['No', 'Yes']])

In [37]:
oe_ar = oe.fit_transform(df)

In [38]:
new_df = pd.DataFrame(oe_ar, columns=df.columns)

In [39]:
new_df

    gender  cough  has_covid
0      1.0    0.0        0.0
1      1.0    0.0        1.0
2      1.0    0.0        0.0
3      0.0    0.0        0.0
4      0.0    0.0        0.0
..     ...    ...        ...
85     0.0    0.0        0.0
86     0.0    1.0        1.0
87     0.0    0.0        0.0
88     0.0    1.0        0.0
89     0.0    1.0        1.0

[90 rows x 3 columns]

In [41]:
# Second way ===>>>

In [43]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [44]:
from sklearn.preprocessing import OrdinalEncoder

In [47]:
oe = OrdinalEncoder(categories=[['Female', 'Male'],['Mild', 'Strong']])

In [50]:
oe_ar_input = oe.fit_transform(x)

In [52]:
from sklearn.preprocessing import LabelEncoder

In [53]:
le = LabelEncoder()

In [54]:
le_ar_output = le.fit_transform(y)