In [19]:
import numpy as np 
import pandas as pd

In [20]:
df = pd.read_csv('tips - tips.csv')
df.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [21]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [22]:
df.drop(columns=['tip', 'day'], inplace=True)

In [23]:
x = df.drop(columns='total_bill')
y = df['total_bill']

In [24]:
x.head(3)

      sex smoker  day    time  size
0  Female     No  Sun  Dinner     2
1    Male     No  Sun  Dinner     3
2    Male     No  Sun  Dinner     3

In [25]:
from sklearn.preprocessing import OrdinalEncoder

In [28]:
oe = OrdinalEncoder(categories=[['Female', 'Male'], ['No', 'Yes'], ['Lunch', 'Dinner']])

In [32]:
x_oe_ar = oe.fit_transform(x[['sex', 'smoker', 'time']])