In [122]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.preprocessing import LabelEncoder 
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [123]:
df = pd.read_csv('tips - tips.csv')
df.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [124]:
le = LabelEncoder()

In [125]:
df['sex'] = le.fit_transform(df['sex'])
df['smoker'] = le.fit_transform(df['smoker'])
df['day'] = le.fit_transform(df['day'])
df['time'] = le.fit_transform(df['time'])

In [126]:
df.head(3)

   total_bill   tip  sex  smoker  day  time  size
0       16.99  1.01    0       0    2     0     2
1       10.34  1.66    1       0    2     0     3
2       21.01  3.50    1       0    2     0     3

In [127]:
from sklearn.model_selection import train_test_split

In [128]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['total_bill']), df['total_bill'], test_size=0.20, random_state=42)

In [129]:
from sklearn.linear_model import LinearRegression

In [130]:
lr = LinearRegression()

In [131]:
lr.fit(x_train, y_train)

LinearRegression()

In [132]:
y_pred = lr.predict(x_test)

In [133]:
y_test.values

array([19.82,  8.77, 24.55, 25.89, 13.  , 17.89, 28.44, 12.48, 14.78,
       15.38, 18.29, 10.77, 10.65, 14.48, 10.07, 18.64, 18.71, 21.58,
       16.45, 41.19, 20.69, 20.65, 14.31,  9.55, 20.9 , 11.69, 10.27,
       25.28, 16.49, 48.17, 38.07,  7.74, 17.81, 20.29, 16.97, 24.08,
       12.03, 43.11, 13.16, 22.67, 10.51, 14.52, 23.95, 10.33, 10.34,
        3.07, 10.59, 18.69,  7.56])

In [135]:
lr_mse = mean_squared_error(y_test, y_pred)
lr_r2 = r2_score(y_test, y_pred)
print('MSE: ', lr_mse)
print('R2 score: ', lr_r2)
print('cofficients: ', lr.coef_)

MSE:  31.076874287778413
R2 score:  0.6334779105328123
cofficients:  [ 2.92515954  0.79318136  2.78821472  0.26813956 -2.57096066  3.05547375]

# Lasso

In [138]:
from sklearn.linear_model import LassoCV
lasso_cv = LassoCV(
    alphas = [0.001,0.01,0.1,1,10],
    cv = 5,
    random_state = 42
)
lasso_cv.fit(x_train, y_train)
print('Alpha : ', lasso_cv.alpha_)

Alpha :  0.001

In [139]:
lasso_model = Lasso(alpha=0.001)
lasso_model.fit(x_train,y_train)

Lasso(alpha=0.001)

In [140]:
lasso_pred = lasso_model.predict(x_test)

In [141]:
lasso_pred

array([18.44828735, 15.259514  , 21.36930256, 33.1318991 , 14.95336813,
       18.04120533, 17.38169389, 13.69284274, 18.85765651, 19.65017098,
       18.18483311, 13.44599166, 10.70901724, 18.04120533,  8.61947826,
       13.35436685, 24.6490477 , 20.8761267 , 15.58116372, 30.90246405,
       21.6324459 , 22.00048588, 22.8385933 , 13.38748528, 24.69393122,
       13.86867278, 14.41117145, 25.76391241, 21.36930256, 36.25504848,
       24.16504651, 16.13992342, 22.10080786, 21.31773826, 21.91223989,
       20.97275895, 16.05233937, 29.83911404, 14.36566613, 17.77810213,
       12.80242146, 12.1716768 , 16.86843951, 16.55890591, 15.74351519,
       11.00774167, 15.84708061, 18.958154  , 11.32364515])

In [142]:
lasso_mse = mean_squared_error(y_test, lasso_pred)
lasso_r2 = r2_score(y_test, lasso_pred)

print('MSE: ', lasso_mse)
print('R2 score: ', lasso_r2)
print('cofficients: ', lasso_model.coef_)

MSE:  31.07499035233191
R2 score:  0.6335001297544072
cofficients:  [ 2.92531912  0.79014706  2.78169133  0.2631032  -2.56079334  3.05489428]

# Ridge

In [144]:
from sklearn.linear_model import RidgeCV
ridge_cv = RidgeCV(
    alphas = [0.001,0.01,0.1,1,10],
    cv = 5
    # random_state = 42
)
ridge_cv.fit(x_train, y_train)
print('Alpha : ', ridge_cv.alpha_)

Alpha :  1.0

In [145]:
ridge_model = Ridge(alpha=1)

In [146]:
ridge_model.fit(x_train, y_train)

Ridge(alpha=1)

In [147]:
ridge_pred = ridge_model.predict(x_test)

In [148]:
ridge_pred

array([18.48593879, 15.25746725, 21.34087815, 33.07056714, 14.93470055,
       17.96497922, 17.3663454 , 13.74876779, 18.85658731, 19.64938636,
       18.18358112, 13.48228407, 10.76413164, 17.96497922,  8.68804376,
       13.39618115, 24.62165483, 20.87560588, 15.61537686, 30.92366764,
       21.64026549, 22.0250836 , 22.79984306, 13.42376179, 24.6028344 ,
       13.92730496, 14.40889422, 25.72595693, 21.34087815, 36.20263068,
       24.15140044, 16.10201263, 22.11141405, 21.28123418, 21.89532242,
       21.00262424, 16.05323664, 29.79645307, 14.42177398, 17.7406364 ,
       12.83853902, 12.22718857, 16.86682988, 16.54053404, 15.72772163,
       10.97979599, 15.8064309 , 18.98192518, 11.38158589])

In [149]:
ridge_mse = mean_squared_error(y_test, ridge_pred)
ridge_r2 = r2_score(y_test, ridge_pred)
print('MSE: ', ridge_mse)
print('R2 score: ', ridge_r2)
print('cofficients: ', ridge_model.coef_)

MSE:  31.036866232286787
R2 score:  0.6339497673855485
cofficients:  [ 2.92611387  0.79302109  2.70751197  0.22434282 -2.46160041  3.04170545]

# ElasticNet

In [151]:
from sklearn.linear_model import ElasticNetCV
elastic_cv = ElasticNetCV(
    l1_ratio = [0.1,0.3,0.5,0.7,0.9,1],
    alphas = [0.001,0.01,0.1,1,10],
    cv = 5,
    random_state = 42
)
elastic_cv.fit(x_train, y_train)
print('Alpha : ', elastic_cv.alpha_)
print('l1_ratio : ', elastic_cv.l1_ratio_)

Alpha :  0.01
l1_ratio :  0.1

In [152]:
elastic_model = ElasticNet(alpha=0.01, l1_ratio=0.1)
elastic_model.fit(x_train, y_train)

ElasticNet(alpha=0.01, l1_ratio=0.1)

In [153]:
elastic_pred = elastic_model.predict(x_test)

In [154]:
elastic_pred

array([18.51714873, 15.25291892, 21.31411384, 33.01717716, 14.92043218,
       17.89674453, 17.3484639 , 13.79852783, 18.85284806, 19.65575511,
       18.17969058, 13.51236919, 10.81322073, 17.89674453,  8.74845792,
       13.43407016, 24.59361255, 20.87232051, 15.65010127, 30.93775352,
       21.65276075, 22.04529738, 22.77188752, 13.45383376, 24.5284599 ,
       13.97294537, 14.40415514, 25.69865919, 21.31411384, 36.15562375,
       24.1370597 , 16.06839165, 22.11985546, 21.2487775 , 21.88463429,
       21.03043142, 16.05463721, 29.76194209, 14.47168531, 17.70738378,
       12.86847942, 12.27660656, 16.86264333, 16.52864215, 15.70947176,
       10.96097508, 15.77690325, 19.00145485, 11.42665402])

In [155]:
elastic_mse = mean_squared_error(y_test, ridge_pred)
elastic_r2 = r2_score(y_test, lasso_pred)
print('MSE: ', elastic_mse)
print('R2 score: ', elastic_r2)
print('cofficients: ', elastic_model.coef_)

MSE:  31.036866232286787
R2 score:  0.6335001297544072
cofficients:  [ 2.92677166  0.78903959  2.64382561  0.18936075 -2.37663352  3.03059746]

In [156]:
# Regularization Techniques -> 
#  -> These techniques are use to reduce the overfitting 

# 1. Ridge => 
#  -> it changes the coefficients near to the zero
#  -> It does not change the coefficients to exactly zero 

# 2. Lasso => 
#  -> It changes the coefficients value to the zero 


# 3. Elastic Net => 
#  -> It is a combination of Ridge and Lasso 
#  -> It can make coefficients to zero or it can changes them near to the zero 

# ==================================================================================

# a. MAE
#  -> It stands for Mean Absolut Error
#  -> When we want to treat the errors as same 
#  -> for example there are two errors 
# 	5 and -5 the both treat as same 

# b. MSE
#  -> It stands for mean square error
#  -> it squared the error and then find it's mean 
#  -> It makes the errors differentiable 
#  -> It makes the large errors more large 
#  -> It affects the units
#  -> example => 
# 	2, 10 => 4, 100

# c. RMSE
#  -> It stands for Root mean square error 
#  -> it is the root value of MSE 
#  -> It does not affect the unit

# d. R2 score
#  -> When we wants to know that how much our model is correct