In [7]:
import pandas as pd

In [8]:
df = pd.DataFrame({
    "colors" : ["green", "red", "blue", "yellow"],
    "Education" : ["High School", "Intermediate", "Bachelors", "Masters"]
})

### One hot encoding

In [9]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)
encoded_data = encoder.fit_transform(df[["colors"]])
pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out())

   colors_blue  colors_green  colors_red  colors_yellow
0          0.0           1.0         0.0            0.0
1          0.0           0.0         1.0            0.0
2          1.0           0.0         0.0            0.0
3          0.0           0.0         0.0            1.0

### Ordinal Encoding

In [17]:
from sklearn.preprocessing import OrdinalEncoder

ord_encoder = OrdinalEncoder(categories = [["High School", "Intermediate", "Bachelors", "Masters"]])
encoded_data = ord_encoder.fit_transform(df[["Education"]])
df["encoded_Education"] = encoded_data
df

   colors     Education  encoded_Education
0   green   High School                0.0
1     red  Intermediate                1.0
2    blue     Bachelors                2.0
3  yellow       Masters                3.0

DATA DIVIDATION

In [19]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [21]:
x = df.drop(columns=["median_house_value"])
y = df["median_house_value"]

In [22]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)