In [18]:
import pandas as pd
import numpy as np

In [23]:
df = pd.read_csv('insurance - insurance.csv')
df.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [24]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [25]:
df.drop(columns=['region'], inplace=True)

In [26]:
df['sex'] = df['sex'].map({'female':0, 'male':1})
df['smoker'] = df['smoker'].map({'no':0, 'yes':1})

In [28]:
x = df.drop(columns = 'smoker')
y = df['smoker']

In [29]:
from sklearn.model_selection import train_test_split

In [39]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.20, random_state=42)

In [40]:
from sklearn.preprocessing import StandardScaler

In [41]:
sc = StandardScaler()

In [42]:
x_train_sc = sc.fit_transform(x_train)

In [48]:
x_test = sc.transform(x_test)

In [43]:
x_train.describe()

               age          sex          bmi     children       charges
count  1070.000000  1070.000000  1070.000000  1070.000000   1070.000000
mean     39.357009     0.512150    30.560397     1.107477  13346.089736
std      14.073960     0.500086     6.043386     1.215983  12019.510778
min      18.000000     0.000000    15.960000     0.000000   1121.873900
25%      27.000000     0.000000    26.205000     0.000000   4897.667387
50%      39.500000     1.000000    30.210000     1.000000   9575.442100
75%      51.000000     1.000000    34.496250     2.000000  16746.657400
max      64.000000     1.000000    53.130000     5.000000  62592.873090

In [46]:
x_train_new = pd.DataFrame(x_train_sc, columns=x_train.columns)

In [47]:
x_train_new.describe()

                age           sex           bmi      children       charges
count  1.070000e+03  1.070000e+03  1.070000e+03  1.070000e+03  1.070000e+03
mean  -1.992176e-16 -6.308557e-17 -4.648410e-17 -2.324205e-17  7.304645e-17
std    1.000468e+00  1.000468e+00  1.000468e+00  1.000468e+00  1.000468e+00
min   -1.518194e+00 -1.024602e+00 -2.417060e+00 -9.111921e-01 -1.017507e+00
25%   -8.784157e-01 -1.024602e+00 -7.210253e-01 -9.111921e-01 -7.032210e-01
50%    1.016470e-02  9.759891e-01 -5.800739e-02 -8.842793e-02 -3.138573e-01
75%    8.276587e-01  9.759891e-01  6.515707e-01  7.343363e-01  2.830529e-01
max    1.751782e+00  9.759891e-01  3.736342e+00  3.202629e+00  4.099153e+00