In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('tips - tips.csv')
df.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [3]:
df.empty

False

In [7]:
df.drop(columns=['day'], inplace=True)

In [9]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [10]:
df['sex'] = df['sex'].map({'Female':0, 'Male':1})
df['smoker'] = df['smoker'].map({'No':0, 'Yes':1})
df['time'] = df['time'].map({'Lunch':0, 'Dinner':1})

In [13]:
x = df.drop(columns=['total_bill'])
y = df['total_bill']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=42)

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
sc = StandardScaler()

In [19]:
x_train_sc = sc.fit_transform(x_train) 
x_train_new = pd.DataFrame(x_train, columns=x_train.columns)

In [23]:
np.round(x_train_new.describe())

         tip    sex  smoker   time   size
count  195.0  195.0   195.0  195.0  195.0
mean     3.0    1.0     0.0    1.0    3.0
std      1.0    0.0     0.0    0.0    1.0
min      1.0    0.0     0.0    0.0    1.0
25%      2.0    0.0     0.0    0.0    2.0
50%      3.0    1.0     0.0    1.0    2.0
75%      4.0    1.0     1.0    1.0    3.0
max     10.0    1.0     1.0    1.0    6.0

In [26]:
x_test.head(3)

      tip  sex  smoker  time  size
24   3.18    1       0     1     2
6    2.00    1       0     1     2
153  2.00    1       0     1     4

In [27]:
x_test_sc = sc.transform(x_test)

In [30]:
pd.DataFrame(x_test_sc, columns=x_test.columns).head(3)

        tip       sex    smoker      time      size
0  0.064688  0.731733 -0.790569  0.610933 -0.612141
1 -0.763161  0.731733 -0.790569  0.610933 -0.612141
2 -0.763161  0.731733 -0.790569  0.610933  1.519421

In [31]:
x_test_sc1 = sc.fit_transform(x_test)
pd.DataFrame(x_test_sc1, columns=x_test.columns).head(3)

        tip       sex    smoker      time      size
0  0.481171  0.795822 -0.762001  0.664211 -0.556022
1 -0.574265  0.795822 -0.762001  0.664211 -0.556022
2 -0.574265  0.795822 -0.762001  0.664211  1.462132