In [192]:
# this is coffee datasset . You have to :
# 1. Check missing data if present then handling it. 
# 2. Encode data 
# 3. Apply Standardization 
# 4. Apply Normalization 
# 5. Filter 30-40 Indexed data using pandas 
# 6. Rename a column name

In [193]:
import numpy as np 
import pandas as pd

In [194]:
df = pd.read_csv('Coffe_sales - Coffe_sales.csv')
df.drop(columns=['Date', 'Time'], inplace=True)
df.head(3)

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,10,card,38.7,Latte,Morning,Fri,Mar,5,3
1,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3
2,12,card,38.7,Hot Chocolate,Afternoon,Fri,Mar,5,3

In [195]:
# 1. Check missing data if present then handling it.

In [196]:
df.isnull().sum()

hour_of_day    0
cash_type      0
money          0
coffee_name    0
Time_of_Day    0
Weekday        0
Month_name     0
Weekdaysort    0
Monthsort      0
dtype: int64

In [197]:
# 2. Encode data

In [198]:
from sklearn.preprocessing import LabelEncoder

In [199]:
le = LabelEncoder()

In [200]:
df['cash_type'].value_counts()

cash_type
card    3547
Name: count, dtype: int64

In [201]:
df['cash_type'] = le.fit_transform(df['cash_type'])
df['coffee_name'] = le.fit_transform(df['coffee_name'])
df['Time_of_Day'] = le.fit_transform(df['Time_of_Day'])
df['Weekday'] = le.fit_transform(df['Weekday'])
df['Month_name'] = le.fit_transform(df['Month_name'])

In [202]:
df.head(3)

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,10,0,38.7,7,1,0,7,5,3
1,12,0,38.7,6,0,0,7,5,3
2,12,0,38.7,6,0,0,7,5,3

In [203]:
# a = pd.get_dummies(df,columns=['cash_type', 'coffee_name', 'Time_of_Day', 'Weekday', 'Month_name'], dtype=np.int32, drop_first=True)

In [204]:
# 3. Apply Standardization

In [205]:
x = df.drop(columns=['money'])
y = df['money']

In [206]:
from sklearn.model_selection import train_test_split

In [207]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [208]:
x_train.describe()

,hour_of_day,cash_type,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
count,2837.000000,2837.0,2837.000000,2837.000000,2837.000000,2837.000000,2837.000000,2837.000000
mean,14.158266,0.0,3.180825,0.985548,3.013042,6.005992,3.830807,6.449418
std,4.234485,0.0,2.591502,0.815144,2.044681,3.386113,1.964314,3.504480
min,6.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
25%,10.000000,0.0,1.000000,0.000000,1.000000,3.000000,2.000000,3.000000
50%,14.000000,0.0,2.000000,1.000000,3.000000,7.000000,4.000000,7.000000
75%,18.000000,0.0,6.000000,2.000000,5.000000,9.000000,5.000000,10.000000
max,22.000000,0.0,7.000000,2.000000,6.000000,11.000000,7.000000,12.000000

In [209]:
from sklearn.preprocessing import StandardScaler

In [210]:
sc = StandardScaler()

In [211]:
x_train_sc = sc.fit_transform(x_train)

In [212]:
new_x_train = pd.DataFrame(x_train_sc, columns=x_train.columns)

In [213]:
np.round(new_x1_train.describe(), 2)

,hour_of_day,cash_type,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
count,2837.00,2837.0,2837.00,2837.00,2837.00,2837.00,2837.00,2837.00
mean,0.00,0.0,-0.00,0.00,-0.00,0.00,0.00,-0.00
std,1.00,0.0,1.00,1.00,1.00,1.00,1.00,1.00
min,-1.93,0.0,-1.23,-1.21,-1.47,-1.77,-1.44,-1.56
25%,-0.98,0.0,-0.84,-1.21,-0.98,-0.89,-0.93,-0.98
50%,-0.04,0.0,-0.46,0.02,-0.01,0.29,0.09,0.16
75%,0.91,0.0,1.09,1.24,0.97,0.88,0.60,1.01
max,1.85,0.0,1.47,1.24,1.46,1.48,1.61,1.58

In [214]:
# Normalization

In [215]:
x1 = df.drop(columns=['money'])
y1 = df['money']

In [216]:
from sklearn.model_selection import train_test_split

In [217]:
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, test_size=0.2, random_state=42)

In [218]:
x1_train.describe()

,hour_of_day,cash_type,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
count,2837.000000,2837.0,2837.000000,2837.000000,2837.000000,2837.000000,2837.000000,2837.000000
mean,14.158266,0.0,3.180825,0.985548,3.013042,6.005992,3.830807,6.449418
std,4.234485,0.0,2.591502,0.815144,2.044681,3.386113,1.964314,3.504480
min,6.000000,0.0,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
25%,10.000000,0.0,1.000000,0.000000,1.000000,3.000000,2.000000,3.000000
50%,14.000000,0.0,2.000000,1.000000,3.000000,7.000000,4.000000,7.000000
75%,18.000000,0.0,6.000000,2.000000,5.000000,9.000000,5.000000,10.000000
max,22.000000,0.0,7.000000,2.000000,6.000000,11.000000,7.000000,12.000000

In [219]:
from sklearn.preprocessing import MinMaxScaler

In [220]:
mn = MinMaxScaler()

In [221]:
x1_train_mn = mn.fit_transform(x1_train)

In [222]:
new_x1_train = pd.DataFrame(x1_train_mn, columns=x1_train.columns)

In [223]:
np.round(new_x1_train.describe(), 2)

,hour_of_day,cash_type,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
count,2837.00,2837.0,2837.00,2837.00,2837.00,2837.00,2837.00,2837.00
mean,0.51,0.0,0.45,0.49,0.50,0.55,0.47,0.50
std,0.26,0.0,0.37,0.41,0.34,0.31,0.33,0.32
min,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00
25%,0.25,0.0,0.14,0.00,0.17,0.27,0.17,0.18
50%,0.50,0.0,0.29,0.50,0.50,0.64,0.50,0.55
75%,0.75,0.0,0.86,1.00,0.83,0.82,0.67,0.82
max,1.00,0.0,1.00,1.00,1.00,1.00,1.00,1.00

In [224]:
# 5. Filter 30-40 Indexed data using pandas

In [225]:
df.iloc[30:40, :]     # first column

,hour_of_day,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
30,9,0,38.7,7,1,5,7,2,3
31,14,0,38.7,7,0,5,7,2,3
32,17,0,38.7,7,2,5,7,2,3
33,17,0,38.7,6,2,5,7,2,3
34,17,0,38.7,3,2,5,7,2,3
35,17,0,38.7,6,2,5,7,2,3
36,17,0,38.7,6,2,5,7,2,3
37,17,0,28.9,4,2,5,7,2,3
38,18,0,38.7,6,2,5,7,2,3
39,13,0,28.9,0,0,6,7,3,3

In [226]:
# 6. Rename a column name

In [227]:
df.rename(columns={'hour_of_day':'Day_hours'}, inplace=True)

In [228]:
df

,Day_hours,cash_type,money,coffee_name,Time_of_Day,Weekday,Month_name,Weekdaysort,Monthsort
0,10,0,38.70,7,1,0,7,5,3
1,12,0,38.70,6,0,0,7,5,3
2,12,0,38.70,6,0,0,7,5,3
3,13,0,28.90,0,0,0,7,5,3
4,13,0,38.70,7,0,0,7,5,3
...,...,...,...,...,...,...,...,...,...
3542,10,0,35.76,2,1,3,7,7,3
3543,14,0,35.76,3,0,3,7,7,3
3544,14,0,35.76,3,0,3,7,7,3
3545,15,0,25.96,0,0,3,7,7,3
3546,18,0,35.76,7,2,3,7,7,3