In [4]:
# Encoding -3 :: get_dummies 
# Column --> has['has_covid'] --> when we apply get_dummies --> 2 columns create --> has_covid_yes, has_covid_no

In [5]:
import numpy as np 
import pandas as pd

In [6]:
df = pd.read_csv('insurance - insurance.csv')
df.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [7]:
a = pd.get_dummies(df, columns=['sex', 'smoker', 'region'])

In [10]:
a = a.astype(int)
a.head(3)

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27,0,16884,1,0,0,1,0,0,0,1
1,18,33,1,1725,0,1,1,0,0,0,1,0
2,28,33,3,4449,0,1,1,0,0,0,1,0

In [11]:
# if I have multiple sub categories --> 1 column drop --> data multiconielity 
# issu resolve 
# model --> overfitting  
#  1 student --> 2 days exam --> exam paper --> exam clear 
# but 3 days --> question answer -->  xxx

In [12]:
b = pd.get_dummies(df, columns=['sex', 'smoker', 'region'], drop_first=True)

In [13]:
b = b.astype(int)