In [1]:
# Encoding --> Transform your categorical data into Numerical data.

In [2]:
# 1. LabelEncoder--> has_covid['yes', 'no'] --> value_counts()---> encode --> has_covid[1,0]

In [12]:
import numpy as np 
import pandas as pd

In [13]:
df = pd.read_csv('covid_toy.csv')
df.head(2)

   age gender  fever cough     city has_covid
0   60   Male  103.0  Mild  Kolkata        No
1   27   Male  100.0  Mild    Delhi       Yes

In [14]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [15]:
df.dropna(inplace=True)

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
lb = LabelEncoder()

In [18]:
df['gender'] = lb.fit_transform(df['gender'])
df['cough'] = lb.fit_transform(df['cough'])
df['city'] = lb.fit_transform(df['city'])
df['has_covid'] = lb.fit_transform(df['has_covid'])

In [22]:
df.sample(3)

    age  gender  fever  cough  city  has_covid
38   49       0  101.0      0     1          1
75    5       1  102.0      0     2          1
72   83       0  101.0      0     2          0

In [24]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [27]:
## Apply Standardization for coverting my data into Normal Distribution

In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
sc = StandardScaler()

In [30]:
x_train_sc = sc.fit_transform(x_train)

In [32]:
x_train_new = pd.DataFrame(x_train_sc, columns=x_train.columns)

In [33]:
np.round(x_train_new.describe(), 2)

         age  gender  fever  cough   city
count  72.00   72.00  72.00  72.00  72.00
mean   -0.00   -0.00  -0.00   0.00   0.00
std     1.01    1.01   1.01   1.01   1.01
min    -1.53   -0.75  -1.30  -0.73  -1.20
25%    -0.95   -0.75  -0.83  -0.73  -1.20
50%     0.14   -0.75   0.13  -0.73  -0.24
75%     0.86    1.33   0.72   1.37   0.72
max     1.57    1.33   1.55   1.37   1.69