In [3]:
import numpy as np 
import pandas as pd

In [4]:
df = pd.read_csv('insurance - insurance.csv')
df.head(3)

   age     sex    bmi  children smoker     region     charges
0   19  female  27.90         0    yes  southwest  16884.9240
1   18    male  33.77         1     no  southeast   1725.5523
2   28    male  33.00         3     no  southeast   4449.4620

In [5]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [7]:
df.dropna(inplace=True)

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
lb = LabelEncoder()

In [10]:
df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['region'] = lb.fit_transform(df['region'])

In [11]:
df.head(3)

   age  sex    bmi  children  smoker  region     charges
0   19    0  27.90         0       1       3  16884.9240
1   18    1  33.77         1       0       2   1725.5523
2   28    1  33.00         3       0       2   4449.4620

In [12]:
x = df.drop(columns='charges')
y = df['charges']

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
mn = MinMaxScaler()

In [17]:
x_train_mn = mn.fit_transform(x_train)

In [18]:
x_train_new = pd.DataFrame(x_train_mn, columns=x_train.columns)

In [19]:
np.round(x_train_new.describe(), 2)

           age      sex      bmi  children   smoker   region
count  1070.00  1070.00  1070.00   1070.00  1070.00  1070.00
mean      0.46     0.51     0.39      0.22     0.21     0.50
std       0.31     0.50     0.16      0.24     0.40     0.37
min       0.00     0.00     0.00      0.00     0.00     0.00
25%       0.20     0.00     0.28      0.00     0.00     0.33
50%       0.47     1.00     0.38      0.20     0.00     0.67
75%       0.72     1.00     0.50      0.40     0.00     0.67
max       1.00     1.00     1.00      1.00     1.00     1.00