In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('tips - tips.csv')
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [3]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [4]:
df.dropna(inplace=True)

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
lb = LabelEncoder()

In [8]:
df['sex'] = lb.fit_transform(df['sex'])
df['smoker'] = lb.fit_transform(df['smoker'])
df['day'] = lb.fit_transform(df['day'])
df['time'] = lb.fit_transform(df['time'])

In [9]:
df.sample(3)

     total_bill   tip  sex  smoker  day  time  size
197       43.11  5.00    0       1    3     1     4
72        26.86  3.14    0       1    1     0     2
88        24.71  5.85    1       0    3     1     2

In [10]:
x = df.drop(columns=['total_bill'])
y = df['total_bill']

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [13]:
## Apply normalization

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
mn = MinMaxScaler()

In [17]:
x_train_mn = mn.fit_transform(x_train)

In [18]:
x_train_new = pd.DataFrame(x_train_mn, columns=x_train.columns)

In [19]:
np.round(x_train_new.describe(), 2)

          tip     sex  smoker     day    time    size
count  195.00  195.00  195.00  195.00  195.00  195.00
mean     0.23    0.65    0.38    0.57    0.27    0.31
std      0.16    0.48    0.49    0.31    0.45    0.19
min      0.00    0.00    0.00    0.00    0.00    0.00
25%      0.11    0.00    0.00    0.33    0.00    0.20
50%      0.22    1.00    0.00    0.67    0.00    0.20
75%      0.30    1.00    1.00    0.67    1.00    0.40
max      1.00    1.00    1.00    1.00    1.00    1.00