In [81]:
import numpy as np 
import pandas as pd

In [82]:
df = pd.read_csv('tips - tips.csv')
df.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [83]:
df.shape

(244, 7)

In [84]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [85]:
df.duplicated().sum()

np.int64(1)

In [86]:
df.drop_duplicates(inplace=True)

In [87]:
from sklearn.model_selection import train_test_split

In [88]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['total_bill']), df['total_bill'],
                                                        test_size=0.20, random_state=42)

In [89]:
x_train.head(3)

      tip     sex smoker  day    time  size
115  3.50  Female     No  Sun  Dinner     2
208  2.03    Male    Yes  Sat  Dinner     2
158  2.61  Female     No  Sun  Dinner     2

In [90]:
from sklearn.preprocessing import OneHotEncoder

In [91]:
ohe = OneHotEncoder(drop='first', sparse_output=False)

In [92]:
x_train_encoded_arr = ohe.fit_transform(x_train[['sex', 'smoker', 'day', 'time']])

In [93]:
x_train_encoded.shape

(194, 6)

In [94]:
x_train_num = x_train.drop(columns=x_train[['sex', 'smoker', 'day', 'time']].columns)

In [95]:
x_train_num.shape

(194, 2)

In [96]:
x_train_transformed = np.concatenate((x_train_encoded, x_train_num), axis=1)

In [97]:
x_train_transformed.shape

(194, 8)

In [98]:
from sklearn.compose import ColumnTransformer

In [99]:
transformer = ColumnTransformer(transformers=[
    ('trf1', OneHotEncoder(drop='first', sparse_output=False), ['sex', 'smoker', 'day', 'time']),
], remainder='passthrough')

In [100]:
x_train_transformed1 = transformer.fit_transform(x_train)

In [101]:
x_train_transformed1.shape

(194, 8)

In [105]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[243 rows x 7 columns]

In [108]:
pd.get_dummies(df, columns=['sex', 'smoker', 'day', 'time'], dtype=np.int16, drop_first=True)

,total_bill,tip,size,sex_Male,smoker_Yes,day_Sat,day_Sun,day_Thur,time_Lunch
0,16.99,1.01,2,0,0,0,1,0,0
1,10.34,1.66,3,1,0,0,1,0,0
2,21.01,3.50,3,1,0,0,1,0,0
3,23.68,3.31,2,1,0,0,1,0,0
4,24.59,3.61,4,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,3,1,0,1,0,0,0
240,27.18,2.00,2,0,1,1,0,0,0
241,22.67,2.00,2,1,1,1,0,0,0
242,17.82,1.75,2,1,0,1,0,0,0
243,18.78,3.00,2,0,0,0,0,1,0