In [81]:
import numpy as np 
import pandas as pd

In [82]:
df = pd.read_csv('tips - tips.csv')
df.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

In [83]:
df.shape

(244, 7)

In [84]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [85]:
df.duplicated().sum()

np.int64(1)

In [86]:
df.drop_duplicates(inplace=True)

In [87]:
from sklearn.model_selection import train_test_split

In [88]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['total_bill']), df['total_bill'],
                                                        test_size=0.20, random_state=42)

In [89]:
x_train.head(3)

      tip     sex smoker  day    time  size
115  3.50  Female     No  Sun  Dinner     2
208  2.03    Male    Yes  Sat  Dinner     2
158  2.61  Female     No  Sun  Dinner     2

In [90]:
from sklearn.preprocessing import OneHotEncoder

In [91]:
ohe = OneHotEncoder(drop='first', sparse_output=False)

In [92]:
x_train_encoded_arr = ohe.fit_transform(x_train[['sex', 'smoker', 'day', 'time']])

In [93]:
x_train_encoded.shape

(194, 6)

In [94]:
x_train_num = x_train.drop(columns=x_train[['sex', 'smoker', 'day', 'time']].columns)

In [95]:
x_train_num.shape

(194, 2)

In [96]:
x_train_transformed = np.concatenate((x_train_encoded, x_train_num), axis=1)

In [97]:
x_train_transformed.shape

(194, 8)

In [98]:
from sklearn.compose import ColumnTransformer

In [99]:
transformer = ColumnTransformer(transformers=[
    ('trf1', OneHotEncoder(drop='first', sparse_output=False), ['sex', 'smoker', 'day', 'time']),
], remainder='passthrough')

In [100]:
x_train_transformed1 = transformer.fit_transform(x_train)

In [101]:
x_train_transformed1.shape

(194, 8)